spring:

  config:
    activate:
      on-profile: test

  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa

  cloud:
    gcp:
      sql:
        enabled: false


jwt:
  secret: this_is_jwt_secret_key
