spring:
  config:
    activate:
      on-profile: production

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_MODE}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: Google


springdoc:
  swagger-ui:
    path: /api-docs

jwt:
  secret: ${JWT_SCERET}
server:
  port: 80
