spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa

jwt:
  secret: thisisjwtsecret
aes256:
  key: thisisaes256key
